name: Publish package
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: |
          Release Type
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease
      package:
        description: |
          Package to publish
        required: true
        type: choice
        options:
          - "@geneontology/web-components"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    outputs:
      previous_version: ${{ steps.increment_version.outputs.previous_version }}
      new_version: ${{ steps.increment_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

        # This git user config is recommended by the actions/checkout documentation
        # https://github.com/actions/checkout/tree/v4.2.2?tab=readme-ov-file#push-a-commit-using-the-built-in-token
      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Increment version for ${{ inputs.package }}
        id: increment_version
        run: |
          echo 'previous_version='$(npm pkg get version --workspaces | jq -r '."${{ inputs.package }}"') >> $GITHUB_OUTPUT
          npm version --preid=beta --no-git-tag-version --workspace ${{ inputs.package }} ${{ inputs.release-type }}
          echo 'new_version='$(npm pkg get version --workspaces | jq -r '."${{ inputs.package }}"') >> $GITHUB_OUTPUT

      - name: Commit version change
        run: |
          git commit -a -m "${{ steps.increment_version.outputs.new_version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run build

      - name: Publish to NPM
        run: npm publish --provenance --access public --workspace ${{ inputs.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: website/build

  deploy_docs:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

  create_release:
    runs-on: ubuntu-latest
    needs: publish
    if: ${{ !startsWith(inputs.release-type, 'pre') }}
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.publish.outputs.new_version }}
          generate_release_notes: true
          prerelease: ${{ startsWith(inputs.release-type, 'pre') }}

